"""build_docs.py - writes the pages of every sample, the gallery, the index by technique and the catalogue.

    python tools/build_docs.py                        # write the pages
    python tools/build_docs.py --check                # fail (exit 1) when a page is stale or a card disagrees with its files
    python tools/build_docs.py --samples <folder>     # read the samples of another folder (drafts), pages written there

Two kinds of samples, both read from their own files, never typed twice:
  agent     samples/<id>/agent/<Agent name>/   the pac copilot workspace: settings.mcs.yml (name, model, instructions),
            behaviors/ (skills), capabilities/tools, capabilities/knowledge, workflows/, connectors/
  workflow  samples/<id>/workflows/<Name>-<guid>/metadata.yml + workflow.json: trigger, inputs, outputs, steps,
            connections ; tool/<Name>.mcs.yml when it is attached to an agent
For each sample: README.md (overview: Try it, problem, solution, what it does, how it works, design, limits, files,
tested on) and SETUP.md (one section per path, from the one that asks the least to the one that asks the most).
At the root: README.md (gallery), TECHNIQUES.md, samples.json.
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/PowerAutomateDesktop-CopilotStudio/copilot-studio-samples"
SEMVER = re.compile(r"\d+\.\d+\.\d+")
KIND = {"agent": "Agent", "workflow": "Workflow"}
GENERATED = "<!-- Generated by tools/build_docs.py from sample.yml and the sample files. Edit those, not this file. -->"
JSON_TYPES = {"string": "Text", "number": "Number", "integer": "Number", "boolean": "Boolean", "array": "List", "object": "Record"}
TRIGGERS = {"Skills": "When an agent calls the workflow", "Button": "Manual (Run button)", "Recurrence": "Recurrence"}
BUILD_TALK = re.compile(r"generated by|produced by|\b\w+[-_]\w+\.(?:py|ps1)\b", re.I)   # how a file was made is not for the reader


def anchor(title):
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")


def mcs(path):
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


# ---------- reading an agent workspace ----------

class Agent:
    def __init__(self, ws: Path):
        self.ws = ws
        s = mcs(ws / "settings.mcs.yml")
        self.name = s.get("displayName", ws.name)
        self.schema = s.get("schemaName", "")
        agent = (s.get("configuration") or {}).get("agentSettings") or {}
        self.model = ((agent.get("model") or {}).get("series")) or ""
        segs = ((agent.get("instructions") or {}).get("segments")) or []
        self.instructions = "\n\n".join(seg.get("value", "") for seg in segs if seg.get("kind") == "StaticSegment").strip()
        self.skills, self.tools, self.knowledge = [], [], []
        for f in sorted((ws / "behaviors").glob("*.mcs.yml")) if (ws / "behaviors").exists() else []:
            d = mcs(f)
            if d.get("kind") != "InlineAgentSkill":
                continue
            meta = d.get("mcs.metadata") or {}
            pkg = ws / "behaviors" / f.name[:-len(".mcs.yml")]
            files = [p for p in pkg.rglob("*") if p.is_file() and not p.name.endswith(".mcs.yml")] if pkg.is_dir() else []
            self.skills.append({"name": meta.get("componentName", f.stem), "when": meta.get("description", ""),
                                "file": f.relative_to(ws.parent.parent).as_posix().replace(" ", "%20"), "package": len(files)})
        for kind, bucket in (("tools", self.tools), ("knowledge", self.knowledge)):
            folder = ws / "capabilities" / kind
            for f in sorted(folder.glob("*.mcs.yml")) if folder.exists() else []:
                d = mcs(f)
                meta = d.get("mcs.metadata") or {}
                src = d.get("source") or {}
                bucket.append({"name": meta.get("componentName", f.stem), "what": meta.get("description", ""),
                               "kind": d.get("kind", ""), "source": src.get("kind", ""), "url": src.get("siteUrl", "")})
        self.workflows = [Workflow(p) for p in sorted((ws / "workflows").iterdir())] if (ws / "workflows").exists() else []
        self.connectors = sorted(p.name for p in (ws / "connectors").iterdir()) if (ws / "connectors").exists() else []
        texts = [p.read_text(encoding="utf-8", errors="ignore") for p in ws.rglob("*.yml")]
        self.build_talk = sum(1 for t in texts if BUILD_TALK.search(t))


# ---------- reading a workflow ----------

class Workflow:
    def __init__(self, folder: Path):
        self.folder = folder
        m = mcs(folder / "metadata.yml")
        self.name, self.id, self.description = m.get("name", folder.name), str(m.get("workflowId", "")), m.get("description", "")
        d = json.loads((folder / "workflow.json").read_text(encoding="utf-8"))
        props = d.get("properties", d)
        df = props.get("definition", {})
        self.connections = sorted((props.get("connectionReferences") or {}).keys())
        trig = next(iter((df.get("triggers") or {}).values()), {})
        tkind = trig.get("kind") or trig.get("type", "")
        self.trigger = TRIGGERS.get(tkind, tkind)
        self.agent_tool = tkind == "Skills"
        self.inputs = self._fields((trig.get("inputs") or {}).get("schema") or {})
        self.actions = df.get("actions") or {}
        resp = next((a for a in self._walk(self.actions) if a.get("type") == "Response"), None)
        self.outputs = self._fields(((resp or {}).get("inputs") or {}).get("schema") or {})
        self.steps = [k.replace("_", " ") for k, v in sorted(self.actions.items(), key=lambda kv: self._order(kv, self.actions))]
        self.n_actions = sum(1 for _ in self._walk(self.actions))
        self.build_talk = 1 if BUILD_TALK.search(self.description or "") else 0

    @staticmethod
    def _fields(schema):
        req = set(schema.get("required") or [])
        return [{"name": k, "title": v.get("title", k), "type": JSON_TYPES.get(v.get("type", ""), v.get("type", "")), "what": v.get("description", ""),
                 "required": k in req} for k, v in (schema.get("properties") or {}).items()]

    @classmethod
    def _walk(cls, actions):
        for a in actions.values():
            yield a
            yield from cls._walk(a.get("actions") or {})
            for branch in ("else",):
                yield from cls._walk((a.get(branch) or {}).get("actions") or {})

    @staticmethod
    def _order(kv, actions):
        """Top-level steps in run order: follow runAfter."""
        depth, name, seen = 0, kv[0], set()
        while actions.get(name, {}).get("runAfter") and name not in seen:
            seen.add(name)
            name = next(iter(actions[name]["runAfter"]))
            depth += 1
        return depth


# ---------- one sample ----------

def fig(p, width=None):
    w = f' width="{width}"' if width else ""
    return f'<img src="{p["file"]}" alt="{p["caption"]}"{w}><br><sub>{p["caption"]}</sub>'


def table(head, rows):
    return ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)] + ["| " + " | ".join(r) + " |" for r in rows] + [""]


class Sample:
    def __init__(self, folder: Path, card: dict, techniques: dict, categories: dict):
        self.folder, self.card, self.techniques, self.categories = folder, card, techniques, categories
        self.kind = card.get("kind")
        self.version = str(card.get("version", ""))
        self.zip = f"{card.get('id')}-v{self.version}"
        self.pics = card.get("pictures") or {}
        self.agent, self.workflow, self.tool = None, None, None
        if self.kind == "agent" and (folder / "agent").exists():
            ws = [p for p in (folder / "agent").iterdir() if (p / "settings.mcs.yml").exists()]
            self.agent = Agent(ws[0]) if len(ws) == 1 else None
        if self.kind == "workflow" and (folder / "workflows").exists():
            wf = [p for p in (folder / "workflows").iterdir() if (p / "workflow.json").exists()]
            self.workflow = Workflow(wf[0]) if len(wf) == 1 else None
            tools = sorted((folder / "tool").glob("*.mcs.yml")) if (folder / "tool").exists() else []
            self.tool = tools[0] if tools else None
        self.tests = []
        csv_path = folder / "tests" / "test-set.csv"
        if csv_path.exists():
            import csv
            with csv_path.open(encoding="utf-8") as fh:
                self.tests = list(csv.DictReader(fh))

    def errors(self):
        c, err = self.card, []
        for key in ("id", "version", "title", "summary", "category", "kind", "level", "minutes", "problem", "solution",
                    "techniques", "quick_try", "tested"):
            if key not in c:
                err.append(f"{key}: required (see templates/{c.get('kind', 'agent')}/sample.yml)")
        if err:
            return err
        if c["id"] != self.folder.name:
            err.append(f"id: {c['id']} must be the folder name {self.folder.name}")
        if not SEMVER.fullmatch(self.version):
            err.append("version: x.y.z is required (1.0.0 for a new sample)")
        cl = self.folder / "CHANGELOG.md"
        if not cl.exists() or f"## {self.version}" not in cl.read_text(encoding="utf-8"):
            err.append(f"CHANGELOG.md: a section '## {self.version} - <date>' is required")
        if c["kind"] not in KIND:
            err.append(f"kind: must be one of {sorted(KIND)}")
        if c["category"] not in self.categories:
            err.append(f"category: '{c['category']}' is not in categories.yml")
        for t in c["techniques"]:
            if t not in self.techniques:
                err.append(f"techniques: '{t}' is not in techniques.yml")
        if c["kind"] == "agent":
            if not self.agent:
                err.append("agent/: exactly one agent workspace (a folder with settings.mcs.yml) is required")
            elif not self.agent.instructions:
                err.append("agent: settings.mcs.yml has no instructions")
            if not c["quick_try"].get("try"):
                err.append("quick_try.try: the messages to send in the quick try, each with what to expect")
        if c["kind"] == "workflow":
            if not self.workflow:
                err.append("workflows/: exactly one folder with metadata.yml and workflow.json is required")
            if "expect" not in c["quick_try"]:
                err.append("quick_try.expect: what the first run returns")
        return err

    def warnings(self):
        w = []
        if "result" not in self.pics:
            w.append("pictures.result: no picture of the result yet")
        if not self.card.get("tested"):
            w.append("tested: never tested yet - the pages say so")
        talk = (self.agent.build_talk if self.agent else 0) + (self.workflow.build_talk if self.workflow else 0)
        if talk:
            w.append("a file mentions how the sample was built (tools, scripts): keep only what a reader needs")
        return w

    def requires(self):
        return ", ".join(self.card.get("requires") or ["Copilot Studio"])

    def tested_line(self):
        t = self.card.get("tested") or []
        return f"Tested {t[-1]['date']}" if t else "**Not tested yet**"

    def meta(self):
        c = self.card
        return f"**{KIND[c['kind']]}** · {c['level'].capitalize()} · Requires {self.requires()} · {self.tested_line()} · v{self.version}"

    # --- the ladder, counted from the files ---
    def ladder(self):
        c, q = self.card, self.card["quick_try"]
        paths = []
        if self.kind == "agent":
            a = self.agent
            paths.append({"id": "quick", "title": "Quick try", "what": q.get("says", "The instructions pasted into a new agent."),
                          "asks": [], "needs": "Copilot Studio", "minutes": q.get("minutes", 5)})
            asks = ["the pac CLI signed in to an environment"]
            if a.skills:
                asks.append(f"{len(a.skills)} skill{'s' if len(a.skills) > 1 else ''} (pushed with the agent)")
            if c.get("knowledge"):
                asks.append(f"{len(c['knowledge'])} knowledge file{'s' if len(c['knowledge']) > 1 else ''} to add")
            if a.connectors or any(t["kind"] != "WorkflowTool" for t in a.tools):
                asks.append("connections to create")
            paths.append({"id": "full", "title": "Full agent", "what": "The agent as built: instructions, skills, tools, knowledge.",
                          "asks": asks, "needs": self.requires() + ", pac CLI", "minutes": c["minutes"]})
            if a.skills:
                paths.append({"id": "own", "title": "In your own agent", "what": "Add one of its skills to an agent you already have.",
                              "asks": ["one skill file pushed into your agent"], "needs": "Your agent, pac CLI", "minutes": None})
        else:
            w = self.workflow
            asks = ["an agent workspace to host it (pac CLI)"] + ([f"{len(w.connections)} connection(s)"] if w.connections else [])
            first = "Run it" if not w.agent_tool else "Call it from an agent"
            what = ("Push it, then run it with the sample inputs." if not w.agent_tool
                    else "Push it with its tool file into an agent, then ask the agent.")
            paths.append({"id": "quick", "title": first, "what": q.get("says", what), "asks": asks,
                          "needs": self.requires() + ", pac CLI", "minutes": q.get("minutes", 10)})
            paths.append({"id": "own", "title": "In your own agent or workflow", "what": "Reuse the steps, the inputs and outputs in your own build.",
                          "asks": ["the workflow folder, and the tool file for an agent"], "needs": "Your agent", "minutes": None})
        for i, p in enumerate(paths, 1):
            p["n"], p["anchor"] = i, f"{i}-{anchor(p['title'])}"
        return paths

    def ladder_table(self, prefix):
        rows = []
        for p in self.ladder():
            asks = ", ".join(p["asks"]) if p["asks"] else "Nothing: a new agent"
            asks = asks[0].upper() + asks[1:]
            time = f"{p['minutes']} min" if p["minutes"] is not None else "Depends on your build"
            rows.append([f"**[{p['n']}. {p['title']}]({prefix}#{p['anchor']})**<br>{p['what']}", asks, p["needs"], time])
        return table(["Path", "You create", "Needs", "Time"], rows)

    # --- README.md ---
    def overview(self):
        c = self.card
        md = [GENERATED, "", f"[All samples](../../README.md) › {KIND[c['kind']]}s › {c['category']}", "", f"# {c['title']}", "",
              c["summary"], "", self.meta(), "", '*For e-learning purposes only: try it in a test environment with the sample data, and review it before any real use. [Disclaimer](../../START-HERE.md#disclaimer)*', "",
              f"[**Step-by-step setup**](SETUP.md) · [Download the sample (zip)]({REPO_URL}/releases/download/{self.zip}/{self.zip}.zip) · [Changelog](CHANGELOG.md)", ""]
        if "result" in self.pics:
            md += [fig(self.pics["result"], 720), ""]
        md += ["## Try it", "", "From the path that asks the least to the one that asks the most. Stop at the one you need.", ""]
        md += self.ladder_table("SETUP.md")
        md += ["## Problem", "", c["problem"].strip(), "", "## Solution", "", c["solution"].strip(), ""]
        md += ["**Techniques:** " + " · ".join(f"[{self.techniques[t]['title']}](../../TECHNIQUES.md#{t})" for t in c["techniques"]), ""]
        if self.agent:
            a = self.agent
            md += ["## What the agent does", "", f"Agent `{a.name}` · model `{a.model or 'default'}`.", ""]
            if a.skills:
                md += ["**Skills** - the agent picks one from its description:", ""]
                md += table(["Skill", "Used when"], [[f"[`{s['name']}`]({s['file']})", s["when"]] for s in a.skills])
            if a.tools:
                md += ["**Tools:**", ""] + table(["Tool", "Kind", "What it does"], [[t["name"], t["kind"], t["what"]] for t in a.tools])
            if a.knowledge or c.get("knowledge"):
                rows = [[k["name"], k["source"] + (f" {k['url']}" if k["url"] else ""), k["what"]] for k in a.knowledge]
                rows += [[f"[`{k['file']}`]({k['file']})", "File to add", k["what"]] for k in c.get("knowledge", [])]
                md += ["**Knowledge:**", ""] + table(["Source", "Kind", "What it holds"], rows)
            md += ["## How it works", "", "```mermaid", "flowchart LR", '  U["User message"] --> A["' + a.name + '<br>instructions"]']
            for i, s in enumerate(a.skills):
                md.append(f'  A --> S{i}["skill · {s["name"]}"]')
            for i, t in enumerate(a.tools):
                md.append(f'  A --> T{i}["tool · {t["name"]}"]')
            for i, k in enumerate(a.knowledge + c.get("knowledge", [])):
                md.append(f'  A -.-> K{i}["knowledge · {k.get("name") or Path(k["file"]).name}"]')
            md += ["```", ""]
        if self.workflow:
            w = self.workflow
            md += ["## Inputs and outputs", "", f"Trigger: **{w.trigger}**.", ""]
            if w.inputs:
                md += table(["Inputs", "Type", "Description"], [[f"`{f['name']}`" + ("" if f["required"] else " *(optional)*"), f["type"], f["what"] or f["title"]] for f in w.inputs])
            if w.outputs:
                md += table(["Outputs", "Type", "Description"], [[f"`{f['name']}`", f["type"], f["what"] or f["title"]] for f in w.outputs])
            if w.connections:
                md += ["**Connections:** " + ", ".join(f"`{x}`" for x in w.connections), ""]
            md += ["## How it works", "", "```mermaid", "flowchart LR", f'  T["{w.trigger}"]']
            prev = "T"
            for i, s in enumerate(w.steps):
                md.append(f'  {prev} --> N{i}["{s}"]')
                prev = f"N{i}"
            md += ["```", "", f"{len(w.steps)} steps at the top level, {w.n_actions} actions in all.", ""]
        if c.get("design"):
            d = c["design"]
            md += ["## Design choices", "", d.get("intro", ""), ""]
            md += table(["Approach", "Result", "Verdict"], [[x["approach"], x["result"], x["verdict"]] for x in d.get("alternatives", [])])
        if c.get("performance"):
            md += ["## Performance", ""] + [f"- {p}" for p in c["performance"]] + [""]
        if c.get("limits"):
            md += ["## Limits", ""] + [f"- {l}" for l in c["limits"]] + [""]
        md += ["## Files", ""]
        for p in sorted(self.folder.iterdir(), key=lambda x: x.name.lower()):
            if p.is_dir():
                md.append(f"- [`{p.name}/`]({p.name}/)")
        md += ["", "## Tested on", ""]
        if c.get("tested"):
            md += table(["Date", "Path", "Result", "Note"], [[str(t["date"]), t.get("path", ""), "Pass" if t["result"] == "pass" else t["result"], t.get("note", "")] for t in c["tested"]])
        else:
            md += ["Not tested yet from this repository.", ""]
        if self.tests:
            md += [f"The test set [`tests/test-set.csv`](tests/test-set.csv) holds {len(self.tests)} messages with the expected behaviour.", ""]
        md += [f"Authors: {', '.join(c.get('authors', []))} · [Changelog](CHANGELOG.md) · "
               f"[Report a problem]({REPO_URL}/issues/new?template=sample-does-not-work.yml&title=%5B{c['id']}%5D+)", ""]
        return "\n".join(md)

    # --- SETUP.md ---
    def setup(self):
        c, q = self.card, self.card["quick_try"]
        md = [GENERATED, "", f"[All samples](../../README.md) › [{c['title']}](README.md) › Setup", "", f"# Set up: {c['title']}", "",
              f"{self.tested_line()} · v{self.version}", "", '*For e-learning purposes only: try it in a test environment with the sample data, and review it before any real use. [Disclaimer](../../START-HERE.md#disclaimer)*', "",
              "From the path that asks the least to the one that asks the most. Stop at the one you need.", ""]
        md += self.ladder_table("")
        for p in self.ladder():
            md += [f"## {p['n']}. {p['title']}", ""]
            if self.kind == "agent" and p["id"] == "quick":
                a = self.agent
                md += [f"### {p['n']}.1 Create the agent and paste its instructions", "",
                       f"In Copilot Studio, create a new agent (any name, e.g. `{a.name}`), open its instructions and paste the block below.", "",
                       f"<details><summary>The instructions ({len(a.instructions.splitlines())} lines)</summary>", "",
                       "```text", a.instructions, "```", "", "</details>", "",
                       f"### {p['n']}.2 Send these messages", ""]
                md += table(["Message", "What you should see"], [[f"`{t['message']}`", t["expect"]] for t in q["try"]])
                if q.get("note"):
                    md += ["> [!NOTE]", f"> {q['note']}", ""]
            elif self.kind == "agent" and p["id"] == "full":
                a = self.agent
                ws = f"agent/{a.ws.name}"
                prefix = a.schema.split("_")[0] if "_" in a.schema else "<prefix>"
                md += [f"### {p['n']}.1 Sign in the pac CLI", "", "```text", "pac auth create --environment <your environment URL>", "```", "",
                       f"### {p['n']}.2 Create the agent", "",
                       "The solution package creates the agent; the skills are pushed afterwards into its synchronised copy.", "",
                       "```text",
                       f'pac copilot pack --publisher-prefix {prefix} --project-dir "{ws}" --output-path out',
                       "pac solution import --path out/<the zip written above> --publish-changes",
                       f"pac copilot clone --bot {a.schema} --output-dir clone",
                       f'copy "{ws}/behaviors" into "clone/{a.ws.name}/behaviors"',
                       f'pac copilot push --project-dir "clone/{a.ws.name}"',
                       "```", ""]
                if c.get("knowledge"):
                    md += [f"### {p['n']}.3 Add the knowledge", "", "In Copilot Studio, add each file as a knowledge source of the agent:", ""]
                    md += [f"- [`{k['file']}`]({k['file']}): {k['what']}" for k in c["knowledge"]] + [""]
                md += [f"### {p['n']}.{4 if c.get('knowledge') else 3} Test", "",
                       (f"Send the messages of [`tests/test-set.csv`](tests/test-set.csv) ({len(self.tests)} cases): each row gives "
                        "the skill that should answer and the words that must, or must not, appear." if self.tests else "Send the messages of the quick try."), ""]
            elif self.kind == "agent" and p["id"] == "own":
                md += ["Clone your agent, copy the skill file (and its folder when it has one), push:", "", "```text",
                       "pac copilot clone --bot <your agent schema name> --output-dir mine",
                       'copy "agent/<Agent>/behaviors/<skill>.mcs.yml" into "mine/<Your agent>/behaviors"',
                       'pac copilot push --project-dir "mine/<Your agent>"', "```", ""]
                md += table(["Skill", "File"], [[s["name"], f"[`{s['file']}`]({s['file']})"] for s in self.agent.skills])
            elif self.kind == "workflow" and p["id"] == "quick":
                w = self.workflow
                rel = f"workflows/{w.folder.name}"
                md += [f"### {p['n']}.1 Push it into an agent workspace", "", "Workflows travel inside an agent workspace. Use any agent of your environment:", "",
                       "```text", "pac copilot clone --bot <agent schema name> --output-dir host",
                       f'copy "{rel}" into "host/<Agent>/workflows"']
                if self.tool:
                    md.append(f'copy "tool/{self.tool.name}" into "host/<Agent>/capabilities/tools"')
                md += ['pac copilot push --project-dir "host/<Agent>"', "```", ""]
                if w.connections:
                    md += [f"Then create the connections it uses: {', '.join(f'`{x}`' for x in w.connections)}.", ""]
                md += [f"### {p['n']}.2 {'Ask the agent' if w.agent_tool else 'Run it'}", ""]
                if q.get("inputs"):
                    md += table(["Input", "Value"], [[f"`{k}`", f"`{v}`"] for k, v in q["inputs"].items()])
                if q.get("message"):
                    md += [f"Message to the agent: `{q['message']}`", ""]
                md += ["Expected:", ""] + [f"- {e}" for e in q["expect"]] + [""]
            else:
                md += ["Copy the folder into your own agent workspace and adapt the steps; the inputs and outputs are "
                       "[the contract](README.md#inputs-and-outputs)." if self.workflow else "", ""]
        if c.get("troubleshooting"):
            md += ["## Troubleshooting", ""] + table(["Symptom", "Fix"], [[t["when"], t["do"]] for t in c["troubleshooting"]])
        return "\n".join(md)


# ---------- root pages ----------

def released(s):
    cl = (s.folder / "CHANGELOG.md").read_text(encoding="utf-8")
    m = re.search(rf"^## {re.escape(s.version)} - (\d{{4}}-\d{{2}}-\d{{2}})", cl, re.M)
    return m.group(1) if m else ""


def gallery(samples, techniques, categories):
    used = {t for s in samples for t in s.card["techniques"]}
    n = len(samples)
    md = [GENERATED, "", "# Copilot Studio samples", "",
          "**The Copilot Studio creations of Anne**, an AI agent specialised in Power Automate Desktop and Copilot "
          "Studio projects. Everything Anne builds is here, in the open: the agent files (instructions, skills, tools), "
          "the workflow definitions, the sample data and the test set of each version.", "",
          "Every sample starts with the quickest way to see it work, then states the problem, the design, what each "
          "part does, its limits and when it was tested.", "",
          f"**{n} sample{'s' if n != 1 else ''}** · {len(used)} techniques · [Samples by technique](TECHNIQUES.md) · "
          f"[How the samples are organised](START-HERE.md) · [Contribute](CONTRIBUTING.md) · "
          f"[Submit a challenge](https://github.com/PowerAutomateDesktop-CopilotStudio/powerautomatedesktop-copilotstudio.github.io/issues/new?template=submit-a-challenge.yml) · "
          "[Power Automate Desktop samples](https://powerautomatedesktop-copilotstudio.github.io/pad-samples/)", "",
          "> [!IMPORTANT]", "> **For e-learning purposes.** The samples teach; they are not production-ready. Read the [disclaimer](START-HERE.md#disclaimer).", "",
          "> [!TIP]", "> **Have an automation challenge?** [Submit it to Anne](https://github.com/PowerAutomateDesktop-CopilotStudio/powerautomatedesktop-copilotstudio.github.io/issues/new?template=submit-a-challenge.yml): the next samples come from your challenges. Private request: [LinkedIn](https://www.linkedin.com/in/franckmongo/).", "",]
    if not samples:
        md += ["> [!NOTE]", "> The first samples are being prepared. [Watch the repository](" + REPO_URL + ") to know when they arrive.", ""]
    if n > 3:
        md += ["## Latest", ""] + [f"- {released(s)} · [{s.card['title']}](samples/{s.folder.name}/README.md) v{s.version}"
                                   for s in sorted(samples, key=lambda s: (released(s), s.card["title"]), reverse=True)[:5]] + [""]
    for kind, label in (("agent", "Agents"), ("workflow", "Workflows")):
        mine = [s for s in samples if s.kind == kind]
        if not mine:
            continue
        md += [f"## {label}", ""]
        for cat in [c for c in categories if any(s.card["category"] == c for s in mine)]:
            md += [f"### {cat}", "", categories[cat]["summary"], ""]
            rows = []
            for s in sorted((x for x in mine if x.card["category"] == cat), key=lambda x: x.card["title"].lower()):
                c, rel, first = s.card, f"samples/{s.folder.name}", s.ladder()[0]
                thumb = f'<img src="{rel}/{c["pictures"]["result"]["file"]}" width="150">' if "result" in s.pics else ""
                try_it = f"{first['minutes']} min, " + (", ".join(first["asks"]) if first["asks"] else "nothing but a new agent")
                rows.append([thumb, f"**[{c['title']}]({rel}/README.md)**<br>{c['summary']}<br><sub>{c['level'].capitalize()} · v{s.version} · {s.tested_line()}</sub>",
                             ", ".join(techniques[t].get("label", t) for t in c["techniques"]), try_it])
            md += table(["", "Sample", "Techniques", "Try it"], rows)
    md += ["## What every sample gives you", "",
           "| Overview (`README.md`) | Setup (`SETUP.md`) |", "|---|---|",
           "| Try it · Problem · Solution · What it does (skills, tools, knowledge) or its inputs and outputs · How it works · "
           "Design choices · Limits · Files · Tested on | The paths from the lightest to the fullest · Troubleshooting |", "",
           "The whole catalogue is also in [`samples.json`](samples.json).", "",
           "## License", "", "[MIT](LICENSE): copy, adapt and use the samples in your own agents and your clients' agents.", ""]
    return "\n".join(md)


def techniques_page(samples, techniques):
    md = [GENERATED, "", "[All samples](README.md)", "", "# Samples by technique", "",
          "A technique is one reusable idea you can carry to another agent or workflow.", ""]
    shown = 0
    for tid, t in techniques.items():
        users = [s for s in samples if tid in s.card["techniques"]]
        if not users:
            continue
        shown += 1
        md += [f'<a id="{tid}"></a>', "", f"## {t['title']}", "", t["summary"], ""]
        md += [f"- [{s.card['title']}](samples/{s.folder.name}/README.md): {s.card['summary']}" for s in users] + [""]
    if not shown:
        md += ["The index fills in as samples arrive.", ""]
    return "\n".join(md)


def catalogue(samples):
    out = []
    for s in sorted(samples, key=lambda x: x.folder.name.lower()):
        c, first = s.card, s.ladder()[0]
        e = {"id": c["id"], "title": c["title"], "summary": c["summary"], "kind": c["kind"], "category": c["category"],
             "level": c["level"], "version": s.version, "released": released(s), "techniques": c["techniques"],
             "quick_try_minutes": first["minutes"], "tested": c.get("tested") or [], "page": f"samples/{s.folder.name}/README.md"}
        if s.agent:
            e.update({"skills": len(s.agent.skills), "tools": len(s.agent.tools), "knowledge": len(s.agent.knowledge) + len(c.get("knowledge", []))})
        if s.workflow:
            e.update({"trigger": s.workflow.trigger, "inputs": len(s.workflow.inputs), "outputs": len(s.workflow.outputs),
                      "connections": s.workflow.connections})
        out.append(e)
    return json.dumps({"samples": out}, indent=2, ensure_ascii=False, default=str) + "\n"


def main():
    check = "--check" in sys.argv
    base = Path(sys.argv[sys.argv.index("--samples") + 1]).resolve() if "--samples" in sys.argv else ROOT / "samples"
    out_root = base.parent if "--samples" in sys.argv else ROOT
    techniques = yaml.safe_load((ROOT / "techniques.yml").read_text(encoding="utf-8"))
    categories = yaml.safe_load((ROOT / "categories.yml").read_text(encoding="utf-8"))
    samples, failed, pages = [], False, {}
    for card_path in sorted(base.glob("*/sample.yml"), key=lambda p: p.parent.name.lower()):
        s = Sample(card_path.parent, yaml.safe_load(card_path.read_text(encoding="utf-8")), techniques, categories)
        errors = s.errors()
        for e in errors:
            print(f"FAIL {s.folder.name}: {e}")
        if errors:
            failed = True
            continue
        for w in s.warnings():
            print(f"WARN {s.folder.name}: {w}")
        pages[s.folder / "README.md"] = s.overview()
        pages[s.folder / "SETUP.md"] = s.setup()
        samples.append(s)
        print(f"ok   {s.folder.name} ({s.kind})")
    pages[out_root / "README.md"] = gallery(samples, techniques, categories)
    pages[out_root / "TECHNIQUES.md"] = techniques_page(samples, techniques)
    pages[out_root / "samples.json"] = catalogue(samples)
    for path, text in pages.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                print(f"FAIL {path.name} is stale, run tools/build_docs.py")
                failed = True
        elif not failed:
            path.write_text(text, encoding="utf-8")
    print(f"{len(samples)} sample(s)")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
